version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 2
    groups:
      root-npm-dependencies:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /example
    schedule:
      interval: weekly
    open-pull-requests-limit: 2
    groups:
      example-npm-dependencies:
        patterns:
          - "*"

  - package-ecosystem: cargo
    directory: /rust
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    groups:
      rust-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    groups:
      github-actions:
        patterns:
          - "*"
