ENV['RCT_NEW_ARCH_ENABLED'] = '1'

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'CslMobileBridgeExample' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Allow non-modular includes
        config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'

        # Clean up flags
        %w[OTHER_CFLAGS OTHER_CPLUSPLUSFLAGS WARNING_CFLAGS].each do |key|
          flags = config.build_settings[key] || []
          if flags.is_a?(String)
            flags = flags.split(" ")
          end
          # Remove ALL -Werror flags
          flags = flags.reject { |f| f.start_with?("-Werror") }
          config.build_settings[key] = flags
        end
      end
    end
    # Force Legacy Build System for Pods project
    installer.pods_project.build_configurations.each do |config|
      config.build_settings['USE_MODERN_BUILD_SYSTEM'] = 'NO'
    end
  end
end
