#import "CslMobileBridge.h"

// Import the generated TurboModule spec header
#import <CslMobileBridgeSpec/CslMobileBridgeSpec.h>

// Import your native C++ bridge installer
#import "NativeCslMobileBridgeModule.h"

#import <ReactCommon/RCTTurboModule.h>
#import <jsi/jsi.h>

@implementation CslMobileBridge

RCT_EXPORT_MODULE(CslMobileBridge)

/**
 * Return the TurboModule generated by codegen
 * and install custom C++ JSI bindings into the runtime
 */
- (std::shared_ptr<facebook::react::TurboModule>)
    getTurboModule:(const facebook::react::ObjCTurboModule::InitParams &)params
{
    // Create the generated TurboModule (from codegen)
    auto module = std::make_shared<facebook::react::NativeCslMobileBridgeSpecJSI>(params);

    // Install your custom JSI bindings into the Hermes runtime
    if (params.runtime != nullptr) {
        cslmobilebridge::CslMobileBridge::install(*params.runtime);
    }

    return module;
}

@end
